#include "WubiPinyinCore.h"

#include <algorithm>
#include <chrono>
#include <cctype>
#include <fstream>
#include <sstream>
#include <string_view>

#ifdef _WIN32
#include <winsqlite/winsqlite3.h>
#include <windows.h>
#pragma comment(lib, "winsqlite3.lib")
#else
#include <sqlite3.h>
#endif

namespace wubipinyin {
namespace {

constexpr int kSchemaVersion = 1;
constexpr int kMinWeight = 1;
constexpr int kMaxWeight = 100000;
constexpr std::size_t kMaxUserTextBytes = 8 * 1024;

std::int64_t NowUnixSeconds() {
  return std::chrono::duration_cast<std::chrono::seconds>(
             std::chrono::system_clock::now().time_since_epoch())
      .count();
}

void SetError(std::string* error, const std::string& value) {
  if (error) {
    *error = value;
  }
}

bool Execute(sqlite3* database, const char* sql, std::string* error) {
  char* message = nullptr;
  const int result = sqlite3_exec(database, sql, nullptr, nullptr, &message);
  if (result == SQLITE_OK) {
    return true;
  }
  SetError(error, message ? message : sqlite3_errmsg(database));
  sqlite3_free(message);
  return false;
}

bool IsAsciiLowercaseCode(std::string_view code,
                          bool allow_apostrophe,
                          std::size_t maximum_length) {
  if (code.empty() || code.size() > maximum_length) {
    return false;
  }
  for (const char ch : code) {
    if (ch >= 'a' && ch <= 'z') {
      continue;
    }
    if (allow_apostrophe && ch == '\'') {
      continue;
    }
    return false;
  }
  return true;
}

bool IsPinyinCode(std::string_view code) {
  if (!IsAsciiLowercaseCode(code, true, 64) || code.front() == '\'' ||
      code.back() == '\'') {
    return false;
  }
  bool previous_was_apostrophe = false;
  bool has_letter = false;
  for (const char ch : code) {
    if (ch == '\'') {
      if (previous_was_apostrophe) {
        return false;
      }
      previous_was_apostrophe = true;
      continue;
    }
    has_letter = true;
    previous_was_apostrophe = false;
  }
  return has_letter;
}

bool ContainsDictionaryUnsafeCharacter(std::string_view value) {
  return value.find_first_of("\r\n\t") != std::string_view::npos;
}

std::string PathUtf8(const std::filesystem::path& path) {
#ifdef _WIN32
  const std::wstring native = path.wstring();
  if (native.empty()) {
    return {};
  }
  const int size = WideCharToMultiByte(CP_UTF8, 0, native.data(),
                                       static_cast<int>(native.size()), nullptr,
                                       0, nullptr, nullptr);
  std::string value(size, '\0');
  WideCharToMultiByte(CP_UTF8, 0, native.data(), static_cast<int>(native.size()),
                      value.data(), size, nullptr, nullptr);
  return value;
#else
  const std::u8string native = path.u8string();
  return {reinterpret_cast<const char*>(native.data()), native.size()};
#endif
}

bool ReplaceFileAtomically(const std::filesystem::path& temporary,
                           const std::filesystem::path& destination,
                           std::string* error) {
#ifdef _WIN32
  if (MoveFileExW(temporary.c_str(), destination.c_str(),
                  MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH)) {
    return true;
  }
  SetError(error, "Could not replace " + PathUtf8(destination));
  return false;
#else
  std::error_code rename_error;
  std::filesystem::rename(temporary, destination, rename_error);
  if (!rename_error) {
    return true;
  }
  SetError(error, rename_error.message());
  return false;
#endif
}

bool WriteDictionary(const std::filesystem::path& destination,
                     const std::string& dictionary_name,
                     const std::vector<UserEntry>& entries,
                     std::string* error) {
  std::filesystem::path temporary = destination;
  temporary += ".tmp";
  std::ofstream file(temporary, std::ios::binary | std::ios::trunc);
  if (!file) {
    SetError(error, "Could not create " + PathUtf8(temporary));
    return false;
  }

  file << "# Rime dictionary\n"
          "# Generated by WubiPinyin. Do not edit this file directly.\n"
          "# encoding: utf-8\n"
          "---\n"
       << "name: " << dictionary_name << "\n"
       << "version: \"1.0\"\n"
          "sort: by_weight\n"
          "...\n";
  for (const UserEntry& entry : entries) {
    file << entry.text << '\t' << entry.code << '\t' << entry.weight << '\n';
  }
  file.flush();
  if (!file) {
    SetError(error, "Could not write " + PathUtf8(temporary));
    return false;
  }
  file.close();
  return ReplaceFileAtomically(temporary, destination, error);
}

bool WriteSchemaOverride(const std::filesystem::path& destination,
                         int candidate_page_size,
                         std::string* error) {
  std::filesystem::path temporary = destination;
  temporary += ".tmp";
  std::ofstream file(temporary, std::ios::binary | std::ios::trunc);
  if (!file) {
    SetError(error, "Could not create " + PathUtf8(temporary));
    return false;
  }

  file << "# Generated by WubiPinyin. Do not edit this file directly.\n"
          "patch:\n"
       << "  \"menu/page_size\": " << candidate_page_size << '\n';
  file.flush();
  if (!file) {
    SetError(error, "Could not write " + PathUtf8(temporary));
    return false;
  }
  file.close();
  return ReplaceFileAtomically(temporary, destination, error);
}

}  // namespace

SettingsStore::~SettingsStore() {
  Close();
}

bool SettingsStore::Open(const std::filesystem::path& database_path,
                         std::string* error) {
  if (error) {
    error->clear();
  }
  std::lock_guard lock(mutex_);
  if (database_) {
    return true;
  }

  std::error_code directory_error;
  std::filesystem::create_directories(database_path.parent_path(), directory_error);
  if (directory_error) {
    SetError(error, directory_error.message());
    return false;
  }

  sqlite3* database = nullptr;
  const int result = sqlite3_open_v2(
      PathUtf8(database_path).c_str(), &database,
      SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE | SQLITE_OPEN_FULLMUTEX, nullptr);
  if (result != SQLITE_OK) {
    SetError(error, database ? sqlite3_errmsg(database) : "Could not open SQLite");
    sqlite3_close(database);
    return false;
  }

  database_ = database;
  sqlite3_busy_timeout(database_, 1000);
  if (!Execute(database_, "PRAGMA foreign_keys = ON;", error) ||
      !Execute(database_, "PRAGMA journal_mode = WAL;", error) ||
      !Execute(database_, "PRAGMA synchronous = NORMAL;", error) ||
      !CreateSchema(error)) {
    sqlite3_close(database_);
    database_ = nullptr;
    return false;
  }
  return true;
}

void SettingsStore::Close() {
  std::lock_guard lock(mutex_);
  if (database_) {
    sqlite3_close(database_);
    database_ = nullptr;
  }
}

bool SettingsStore::CreateSchema(std::string* error) {
  std::ostringstream sql;
  sql << "BEGIN;"
         "CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY);"
         "CREATE TABLE IF NOT EXISTS settings ("
         "  key TEXT PRIMARY KEY NOT NULL,"
         "  value TEXT NOT NULL,"
         "  updated_at INTEGER NOT NULL"
         ");"
         "CREATE TABLE IF NOT EXISTS user_entries ("
         "  id INTEGER PRIMARY KEY AUTOINCREMENT,"
         "  text TEXT NOT NULL,"
         "  scheme TEXT NOT NULL CHECK(scheme IN ('wubi','pinyin')),"
         "  code TEXT NOT NULL,"
         "  weight INTEGER NOT NULL,"
         "  enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN (0,1)),"
         "  created_at INTEGER NOT NULL,"
         "  updated_at INTEGER NOT NULL,"
         "  UNIQUE(scheme, code, text)"
         ");"
         "INSERT OR IGNORE INTO schema_migrations(version) VALUES ("
      << kSchemaVersion << ");"
      << "COMMIT;";
  if (!Execute(database_, sql.str().c_str(), error)) {
    Execute(database_, "ROLLBACK;", nullptr);
    return false;
  }

  const SettingsSnapshot defaults;
  return SetDefaultValue("default_route", RouteName(defaults.default_route), error) &&
         SetDefaultValue("learning_enabled", defaults.learning_enabled ? "1" : "0", error) &&
         SetDefaultValue("password_input_protection",
                         defaults.password_input_protection ? "1" : "0", error) &&
         SetDefaultValue("show_source_labels", defaults.show_source_labels ? "1" : "0", error) &&
         SetDefaultValue("candidate_page_size", std::to_string(defaults.candidate_page_size), error) &&
         SetDefaultValue("theme", defaults.theme, error) &&
         SetDefaultValue("learning_reset_requested", "0", error);
}

bool SettingsStore::SetValue(const std::string& key,
                             const std::string& value,
                             std::string* error) {
  static constexpr char kSql[] =
      "INSERT INTO settings(key, value, updated_at) VALUES(?, ?, ?) "
      "ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;";
  sqlite3_stmt* statement = nullptr;
  if (sqlite3_prepare_v2(database_, kSql, -1, &statement, nullptr) != SQLITE_OK) {
    SetError(error, sqlite3_errmsg(database_));
    return false;
  }
  sqlite3_bind_text(statement, 1, key.c_str(), -1, SQLITE_TRANSIENT);
  sqlite3_bind_text(statement, 2, value.c_str(), -1, SQLITE_TRANSIENT);
  sqlite3_bind_int64(statement, 3, NowUnixSeconds());
  const bool success = sqlite3_step(statement) == SQLITE_DONE;
  if (!success) {
    SetError(error, sqlite3_errmsg(database_));
  }
  sqlite3_finalize(statement);
  return success;
}

bool SettingsStore::SetDefaultValue(const std::string& key,
                                    const std::string& value,
                                    std::string* error) {
  static constexpr char kSql[] =
      "INSERT OR IGNORE INTO settings(key, value, updated_at) VALUES(?, ?, ?);";
  sqlite3_stmt* statement = nullptr;
  if (sqlite3_prepare_v2(database_, kSql, -1, &statement, nullptr) != SQLITE_OK) {
    SetError(error, sqlite3_errmsg(database_));
    return false;
  }
  sqlite3_bind_text(statement, 1, key.c_str(), -1, SQLITE_TRANSIENT);
  sqlite3_bind_text(statement, 2, value.c_str(), -1, SQLITE_TRANSIENT);
  sqlite3_bind_int64(statement, 3, NowUnixSeconds());
  const bool success = sqlite3_step(statement) == SQLITE_DONE;
  if (!success) {
    SetError(error, sqlite3_errmsg(database_));
  }
  sqlite3_finalize(statement);
  return success;
}

std::optional<std::string> SettingsStore::GetValue(const std::string& key,
                                                    std::string* error) const {
  static constexpr char kSql[] = "SELECT value FROM settings WHERE key = ?;";
  sqlite3_stmt* statement = nullptr;
  if (sqlite3_prepare_v2(database_, kSql, -1, &statement, nullptr) != SQLITE_OK) {
    SetError(error, sqlite3_errmsg(database_));
    return std::nullopt;
  }
  sqlite3_bind_text(statement, 1, key.c_str(), -1, SQLITE_TRANSIENT);
  std::optional<std::string> result;
  if (sqlite3_step(statement) == SQLITE_ROW) {
    const auto* value = reinterpret_cast<const char*>(sqlite3_column_text(statement, 0));
    result = value ? value : "";
  }
  sqlite3_finalize(statement);
  return result;
}

std::optional<SettingsSnapshot> SettingsStore::ReadSettings(std::string* error) const {
  if (error) {
    error->clear();
  }
  std::lock_guard lock(mutex_);
  if (!database_) {
    SetError(error, "Settings store is not open");
    return std::nullopt;
  }
  SettingsSnapshot snapshot;
  const auto route = GetValue("default_route", error);
  const auto learning = GetValue("learning_enabled", error);
  const auto password_input_protection =
      GetValue("password_input_protection", error);
  const auto labels = GetValue("show_source_labels", error);
  const auto page_size = GetValue("candidate_page_size", error);
  const auto theme = GetValue("theme", error);
  if (!route || !learning || !password_input_protection || !labels ||
      !page_size || !theme) {
    return std::nullopt;
  }
  const auto parsed_route = ParseRoute(*route);
  if (!parsed_route) {
    SetError(error, "Invalid route setting");
    return std::nullopt;
  }
  snapshot.default_route = *parsed_route;
  snapshot.learning_enabled = *learning == "1";
  snapshot.password_input_protection = *password_input_protection == "1";
  snapshot.show_source_labels = *labels == "1";
  try {
    snapshot.candidate_page_size = std::clamp(std::stoi(*page_size), 5, 9);
  } catch (const std::exception&) {
    SetError(error, "Invalid candidate page size");
    return std::nullopt;
  }
  snapshot.theme = *theme;
  return snapshot;
}

bool SettingsStore::WriteSettings(const SettingsSnapshot& settings,
                                  std::string* error) {
  if (error) {
    error->clear();
  }
  if (settings.candidate_page_size < 5 || settings.candidate_page_size > 9 ||
      (settings.theme != "system" && settings.theme != "light" &&
       settings.theme != "dark")) {
    SetError(error, "Invalid settings snapshot");
    return false;
  }
  std::lock_guard lock(mutex_);
  if (!database_) {
    SetError(error, "Settings store is not open");
    return false;
  }
  if (!Execute(database_, "BEGIN;", error)) {
    return false;
  }
  const bool success =
      SetValue("default_route", RouteName(settings.default_route), error) &&
      SetValue("learning_enabled", settings.learning_enabled ? "1" : "0", error) &&
      SetValue("password_input_protection",
               settings.password_input_protection ? "1" : "0", error) &&
      SetValue("show_source_labels", settings.show_source_labels ? "1" : "0", error) &&
      SetValue("candidate_page_size", std::to_string(settings.candidate_page_size), error) &&
      SetValue("theme", settings.theme, error);
  if (!success) {
    Execute(database_, "ROLLBACK;", nullptr);
    return false;
  }
  return Execute(database_, "COMMIT;", error);
}

std::vector<UserEntry> SettingsStore::ListUserEntries(std::string* error) const {
  if (error) {
    error->clear();
  }
  std::lock_guard lock(mutex_);
  std::vector<UserEntry> entries;
  if (!database_) {
    SetError(error, "Settings store is not open");
    return entries;
  }
  static constexpr char kSql[] =
      "SELECT id, text, scheme, code, weight, enabled "
      "FROM user_entries ORDER BY scheme, code, text;";
  sqlite3_stmt* statement = nullptr;
  if (sqlite3_prepare_v2(database_, kSql, -1, &statement, nullptr) != SQLITE_OK) {
    SetError(error, sqlite3_errmsg(database_));
    return entries;
  }
  while (sqlite3_step(statement) == SQLITE_ROW) {
    UserEntry entry;
    entry.id = sqlite3_column_int64(statement, 0);
    entry.text = reinterpret_cast<const char*>(sqlite3_column_text(statement, 1));
    const auto route = ParseRoute(reinterpret_cast<const char*>(sqlite3_column_text(statement, 2)));
    entry.scheme = route.value_or(HybridRoute::kAuto);
    entry.code = reinterpret_cast<const char*>(sqlite3_column_text(statement, 3));
    entry.weight = sqlite3_column_int(statement, 4);
    entry.enabled = sqlite3_column_int(statement, 5) != 0;
    entries.push_back(std::move(entry));
  }
  if (sqlite3_errcode(database_) != SQLITE_OK && sqlite3_errcode(database_) != SQLITE_DONE) {
    SetError(error, sqlite3_errmsg(database_));
  }
  sqlite3_finalize(statement);
  return entries;
}

bool SettingsStore::UpsertUserEntry(UserEntry* entry, std::string* error) {
  if (error) {
    error->clear();
  }
  if (!entry || !ValidateUserEntry(*entry, error)) {
    return false;
  }
  std::lock_guard lock(mutex_);
  if (!database_) {
    SetError(error, "Settings store is not open");
    return false;
  }
  static constexpr char kInsertSql[] =
      "INSERT INTO user_entries(text, scheme, code, weight, enabled, created_at, updated_at) "
      "VALUES(?, ?, ?, ?, ?, ?, ?) "
      "ON CONFLICT(scheme, code, text) DO UPDATE SET "
      "weight=excluded.weight, enabled=excluded.enabled, updated_at=excluded.updated_at;";
  static constexpr char kUpdateSql[] =
      "UPDATE user_entries SET text=?, scheme=?, code=?, weight=?, enabled=?, updated_at=? "
      "WHERE id=?;";
  const char* sql = entry->id ? kUpdateSql : kInsertSql;
  sqlite3_stmt* statement = nullptr;
  if (sqlite3_prepare_v2(database_, sql, -1, &statement, nullptr) != SQLITE_OK) {
    SetError(error, sqlite3_errmsg(database_));
    return false;
  }
  const std::string route = RouteName(entry->scheme);
  const std::int64_t now = NowUnixSeconds();
  sqlite3_bind_text(statement, 1, entry->text.c_str(), -1, SQLITE_TRANSIENT);
  sqlite3_bind_text(statement, 2, route.c_str(), -1, SQLITE_TRANSIENT);
  sqlite3_bind_text(statement, 3, entry->code.c_str(), -1, SQLITE_TRANSIENT);
  sqlite3_bind_int(statement, 4, entry->weight);
  sqlite3_bind_int(statement, 5, entry->enabled ? 1 : 0);
  sqlite3_bind_int64(statement, 6, now);
  if (entry->id) {
    sqlite3_bind_int64(statement, 7, entry->id);
  } else {
    sqlite3_bind_int64(statement, 7, now);
  }
  const int result = sqlite3_step(statement);
  const bool success = result == SQLITE_DONE;
  if (!success) {
    SetError(error, sqlite3_errmsg(database_));
  }
  sqlite3_finalize(statement);
  if (!success) {
    return false;
  }
  if (entry->id) {
    if (sqlite3_changes(database_) == 0) {
      SetError(error, "User entry does not exist");
      return false;
    }
    return true;
  }

  static constexpr char kFindIdSql[] =
      "SELECT id FROM user_entries WHERE scheme=? AND code=? AND text=?;";
  statement = nullptr;
  if (sqlite3_prepare_v2(database_, kFindIdSql, -1, &statement, nullptr) !=
      SQLITE_OK) {
    SetError(error, sqlite3_errmsg(database_));
    return false;
  }
  sqlite3_bind_text(statement, 1, route.c_str(), -1, SQLITE_TRANSIENT);
  sqlite3_bind_text(statement, 2, entry->code.c_str(), -1, SQLITE_TRANSIENT);
  sqlite3_bind_text(statement, 3, entry->text.c_str(), -1, SQLITE_TRANSIENT);
  if (sqlite3_step(statement) != SQLITE_ROW) {
    SetError(error, sqlite3_errmsg(database_));
    sqlite3_finalize(statement);
    return false;
  }
  entry->id = sqlite3_column_int64(statement, 0);
  sqlite3_finalize(statement);
  return true;
}

bool SettingsStore::DeleteUserEntry(std::int64_t id, std::string* error) {
  if (error) {
    error->clear();
  }
  if (id <= 0) {
    SetError(error, "User entry id must be positive");
    return false;
  }
  std::lock_guard lock(mutex_);
  if (!database_) {
    SetError(error, "Settings store is not open");
    return false;
  }
  sqlite3_stmt* statement = nullptr;
  if (sqlite3_prepare_v2(database_, "DELETE FROM user_entries WHERE id=?;", -1,
                         &statement, nullptr) != SQLITE_OK) {
    SetError(error, sqlite3_errmsg(database_));
    return false;
  }
  sqlite3_bind_int64(statement, 1, id);
  const bool success = sqlite3_step(statement) == SQLITE_DONE;
  if (!success) {
    SetError(error, sqlite3_errmsg(database_));
  }
  sqlite3_finalize(statement);
  return success;
}

bool SettingsStore::MaterializeRimeDictionaries(
    const std::filesystem::path& directory,
    std::string* error) const {
  if (error) {
    error->clear();
  }
  const auto settings = ReadSettings(error);
  if (!settings) {
    return false;
  }
  const std::vector<UserEntry> entries = ListUserEntries(error);
  if (error && !error->empty()) {
    return false;
  }
  std::error_code directory_error;
  std::filesystem::create_directories(directory, directory_error);
  if (directory_error) {
    SetError(error, directory_error.message());
    return false;
  }

  std::vector<UserEntry> wubi;
  std::vector<UserEntry> pinyin;
  for (const UserEntry& entry : entries) {
    if (!entry.enabled) {
      continue;
    }
    if (entry.scheme == HybridRoute::kWubi) {
      wubi.push_back(entry);
    } else if (entry.scheme == HybridRoute::kPinyin) {
      pinyin.push_back(entry);
    }
  }
  return WriteDictionary(directory / "hybrid_auto_wubi_user.dict.yaml",
                         "hybrid_auto_wubi_user", wubi, error) &&
         WriteDictionary(directory / "hybrid_auto_pinyin_user.dict.yaml",
                         "hybrid_auto_pinyin_user", pinyin, error) &&
         WriteSchemaOverride(directory / "hybrid_auto.custom.yaml",
                             settings->candidate_page_size, error);
}

bool SettingsStore::RequestLearningReset(std::string* error) {
  if (error) {
    error->clear();
  }
  std::lock_guard lock(mutex_);
  if (!database_) {
    SetError(error, "Settings store is not open");
    return false;
  }
  return SetValue("learning_reset_requested", "1", error);
}

bool SettingsStore::ConsumeLearningResetRequest(std::string* error) {
  if (error) {
    error->clear();
  }
  std::lock_guard lock(mutex_);
  if (!database_) {
    SetError(error, "Settings store is not open");
    return false;
  }
  const auto requested = GetValue("learning_reset_requested", error);
  if (!requested) {
    return false;
  }
  if (*requested != "1") {
    return false;
  }
  return SetValue("learning_reset_requested", "0", error);
}

bool SettingsStore::ValidateUserEntry(const UserEntry& entry, std::string* error) {
  if (entry.text.empty() || entry.text.size() > kMaxUserTextBytes ||
      ContainsDictionaryUnsafeCharacter(entry.text)) {
    SetError(error,
             "User text must not be empty, oversized, or contain a tab or newline");
    return false;
  }
  if (entry.weight < kMinWeight || entry.weight > kMaxWeight) {
    SetError(error, "User entry weight is out of range");
    return false;
  }
  if (entry.scheme == HybridRoute::kWubi) {
    if (!IsAsciiLowercaseCode(entry.code, false, 4)) {
      SetError(error, "Wubi codes must contain one to four lowercase letters");
      return false;
    }
    return true;
  }
  if (entry.scheme == HybridRoute::kPinyin) {
    if (!IsPinyinCode(entry.code)) {
      SetError(error, "Pinyin must use lowercase letters and apostrophes");
      return false;
    }
    return true;
  }
  SetError(error, "User entries must be Wubi or Pinyin, not auto");
  return false;
}

std::string SettingsStore::RouteName(HybridRoute route) {
  switch (route) {
    case HybridRoute::kAuto:
      return "auto";
    case HybridRoute::kWubi:
      return "wubi";
    case HybridRoute::kPinyin:
      return "pinyin";
  }
  return "auto";
}

std::optional<HybridRoute> SettingsStore::ParseRoute(const std::string& value) {
  if (value == "auto") {
    return HybridRoute::kAuto;
  }
  if (value == "wubi") {
    return HybridRoute::kWubi;
  }
  if (value == "pinyin") {
    return HybridRoute::kPinyin;
  }
  return std::nullopt;
}

}  // namespace wubipinyin
